name: Publish bench-runner image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Image version (e.g. v1.2.3)"
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Sanitize version (strip leading v)
        id: vars
        run: echo "version=${VERSION#v}" >> $GITHUB_OUTPUT
        env:
          VERSION: ${{ github.event.inputs.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push bench-runner
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/bench-runner/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/bench-runner-base:${{ steps.vars.outputs.version }}

      - name: Build and push agent-harness
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/agent-harness/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/agent-harness-base:${{ steps.vars.outputs.version }}